/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container": "#1c1f29",
        "secondary-container": "#0566d9",
        "on-primary-fixed": "#25005a",
        "danger": "#EF4444",
        "on-background": "#e0e2ef",
        "primary-fixed": "#eaddff",
        "on-secondary-container": "#e6ecff",
        "surface": "#121724",
        "surface-dim": "#10131c",
        "secondary-fixed-dim": "#adc6ff",
        "secondary-fixed": "#d8e2ff",
        "neon-gold": "#F59E0B",
        "primary": "#d2bbff",
        "tertiary-fixed-dim": "#4edea3",
        "surface-bright": "#363943",
        "surface-container-highest": "#31343f",
        "surface-container-lowest": "#0b0e17",
        "surface-variant": "#31343f",
        "surface-tint": "#d2bbff",
        "border-subtle": "#232C3F",
        "inverse-primary": "#732ee4",
        "text-muted": "#7D8D9F",
        "on-primary-fixed-variant": "#5a00c6",
        "on-primary-container": "#ede0ff",
        "on-secondary-fixed-variant": "#004395",
        "on-primary": "#3f008e",
        "on-surface-variant": "#ccc3d8",
        "on-surface": "#e0e2ef",
        "surface-container-high": "#272a34",
        "on-error-container": "#ffdad6",
        "outline": "#958da1",
        "outline-variant": "#4a4455",
        "on-tertiary-fixed": "#002113",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "on-tertiary": "#003824",
        "error-container": "#93000a",
        "on-tertiary-container": "#76ffc2",
        "on-secondary-fixed": "#001a42",
        "inverse-surface": "#e0e2ef",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-low": "#181b25",
        "text-primary": "#E2E8F0",
        "on-secondary": "#002e6a",
        "primary-fixed-dim": "#d2bbff",
        "tertiary-container": "#007650",
        "inverse-on-surface": "#2d303a",
        "tertiary-fixed": "#6ffbbe",
        "warning": "#F59E0B",
        "primary-container": "#7c3aed",
        "tertiary": "#4edea3",
        "secondary": "#adc6ff",
        "background": "#070A13"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "sidebar-width": "280px",
        "unit": "4px",
        "container-padding": "16px",
        "osd-margin": "8px",
        "gutter": "2px"
      },
      "fontFamily": {
        "sans": ["Pretendard", "Inter", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "title-sm": ["Pretendard", "Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "osd-label": ["Pretendard", "Inter", "sans-serif"],
        "body-base": ["Pretendard", "Inter", "sans-serif"],
        "display-lg": ["Pretendard", "Inter", "sans-serif"],
        "headline-md": ["Pretendard", "Inter", "sans-serif"],
        "body-sm": ["Pretendard", "Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
        "title-sm": ["16px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "osd-label": ["12px", { "lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "700" }],
        "body-base": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "mono-data": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
