import React from 'react'; export const SemanticVectorPortal: React.FC = () => { return ( <>
<main className="flex-1 min-w-0 h-[calc(100vh-3.5rem)] flex flex-col bg-background relative z-10">
<div className="flex-1 flex flex-col p-container-padding gap-4 overflow-hidden">
{/* Header section */}
<header className="flex justify-between items-end shrink-0">
<div>
<h1 className="text-display-lg font-display-lg text-on-surface whitespace-nowrap overflow-hidden text-ellipsis">다차원 의미 벡터 가시화 &amp; 분석 포탈</h1>
<p className="text-body-sm font-body-sm text-text-muted mt-1">t-SNE 투영 (dim=2, perplexity=30) • 실시간 연속 인덱싱 활성화됨</p>
</div>
<div className="flex gap-2">
<button className="px-3 py-1.5 border border-border-subtle bg-surface hover:bg-surface-container-high text-mono-data font-mono-data text-on-surface flex items-center gap-2 rounded transition-colors">
<span className="material-symbols-outlined text-[16px]">refresh</span> 동기화 </button>
<button className="px-3 py-1.5 border border-border-subtle bg-surface hover:bg-surface-container-high text-mono-data font-mono-data text-on-surface flex items-center gap-2 rounded transition-colors">
<span className="material-symbols-outlined text-[16px]">tune</span> 매개변수 </button>
</div>
</header>
{/* Center: 2D Semantic Vector Space (Scatter Plot) */}
<div className="flex-1 bg-surface-dim border border-border-subtle rounded-lg relative overflow-hidden flex flex-col">
{/* Overlay Grid & Axis */}
<div className="absolute inset-0 pointer-events-none" style={{ backgroundImage: "linear-gradient(to right, rgba(35, 44, 63, 0.3) 1px, transparent 1px), linear-gradient(to bottom, rgba(35, 44, 63, 0.3) 1px, transparent 1px)", backgroundSize: "50px 50px" }}></div>
<div className="absolute inset-y-0 left-1/2 w-[1px] bg-border-subtle opacity-50 pointer-events-none"></div>
<div className="absolute inset-x-0 top-1/2 h-[1px] bg-border-subtle opacity-50 pointer-events-none"></div>
{/* Legend Overlay */}
<div className="absolute top-4 right-4 bg-surface-container/80 backdrop-blur border border-border-subtle p-3 rounded shadow-lg z-20">
<div className="text-label-caps font-label-caps text-text-muted mb-2">클러스터 분류</div>
<div className="space-y-2 text-mono-data font-mono-data">
<div className="flex items-center gap-2 text-primary"><div className="w-3 h-3 rounded-full bg-primary"></div> 사람 감지</div>
<div className="flex items-center gap-2 text-tertiary"><div className="w-3 h-3 rounded-full bg-tertiary"></div> 차량 활동</div>
<div className="flex items-center gap-2 text-secondary"><div className="w-3 h-3 rounded-full bg-secondary"></div> 이상 / 알 수 없음</div>
<div className="flex items-center gap-2 text-warning mt-3 pt-2 border-t border-border-subtle">
<span className="material-symbols-outlined text-[14px]">star</span> 활성 쿼리 </div>
</div>
</div>
{/* The Plot Canvas */}
<svg className="w-full h-full relative z-10" id="scatter-plot" preserveAspectRatio="none" viewBox="0 0 1000 600">
{/* Points generated by JS */}
</svg>
{/* Tooltip Overlay (Hidden by default) */}
<div className="absolute hidden bg-surface-container border border-border-subtle p-2 rounded shadow-xl text-mono-data font-mono-data text-on-surface z-30 pointer-events-none whitespace-nowrap" id="plot-tooltip"> ID: <span className="text-primary" id="tt-id"></span><br/> 신뢰도: <span id="tt-conf"></span>
</div>
</div>
{/* Bottom: Real-time Vector Indexing Stats */}
<div className="h-32 shrink-0 grid grid-cols-3 gap-4">
{/* Stat Card 1: Cumulative Embeddings */}
<div className="bg-surface border border-border-subtle rounded-lg p-4 flex flex-col justify-between">
<div className="text-label-caps font-label-caps text-text-muted flex items-center gap-2">
<span className="material-symbols-outlined text-[16px]">database</span> 누적 임베딩 </div>
<div className="flex items-end gap-3">
<div className="text-display-lg font-display-lg text-on-surface tracking-tight">14,285,901</div>
<div className="text-mono-data font-mono-data text-tertiary flex items-center mb-1">
<span className="material-symbols-outlined text-[14px]">arrow_upward</span> 1.2k/s </div>
</div>
<div className="w-full h-1 bg-surface-container-high rounded-full mt-2 overflow-hidden">
<div className="h-full bg-primary w-[78%]"></div>
</div>
</div>
{/* Stat Card 2: DB Latency */}
<div className="bg-surface border border-border-subtle rounded-lg p-4 flex flex-col justify-between relative overflow-hidden">
<div className="text-label-caps font-label-caps text-text-muted flex items-center gap-2 z-10">
<span className="material-symbols-outlined text-[16px]">speed</span> 검색 지연 시간 (P99) </div>
<div className="text-display-lg font-display-lg text-on-surface z-10"> 24<span className="text-title-sm text-text-muted">ms</span>
</div>
{/* Fake Sparkline */}
<div className="absolute bottom-0 left-0 w-full h-12 flex items-end gap-1 px-4 pb-2 opacity-50">
<div className="w-full h-[40%] bg-border-subtle rounded-t"></div>
<div className="w-full h-[30%] bg-border-subtle rounded-t"></div>
<div className="w-full h-[60%] bg-border-subtle rounded-t"></div>
<div className="w-full h-[50%] bg-border-subtle rounded-t"></div>
<div className="w-full h-[80%] bg-primary/40 rounded-t"></div>
<div className="w-full h-[30%] bg-border-subtle rounded-t"></div>
<div className="w-full h-[40%] bg-border-subtle rounded-t"></div>
<div className="w-full h-[20%] bg-border-subtle rounded-t"></div>
<div className="w-full h-[50%] bg-border-subtle rounded-t"></div>
<div className="w-full h-[25%] bg-border-subtle rounded-t"></div>
</div>
</div>
{/* Stat Card 3: Top Cosine Match */}
<div className="bg-surface border border-border-subtle rounded-lg p-4 flex flex-col overflow-hidden">
<div className="text-label-caps font-label-caps text-text-muted flex items-center gap-2 mb-3">
<span className="material-symbols-outlined text-[16px]">target</span> 상위 코사인 일치 (현재 쿼리) </div>
<div className="flex-1 overflow-y-auto space-y-1">
<div className="flex justify-between items-center bg-surface-container-low px-2 py-1 rounded">
<span className="text-mono-data font-mono-data text-on-surface">VEC_0x8F9A2...</span>
<span className="text-mono-data font-mono-data text-tertiary">0.982</span>
</div>
<div className="flex justify-between items-center bg-surface-container-low px-2 py-1 rounded">
<span className="text-mono-data font-mono-data text-on-surface">VEC_0x3B1C4...</span>
<span className="text-mono-data font-mono-data text-tertiary">0.965</span>
</div>
<div className="flex justify-between items-center bg-surface-container-low px-2 py-1 rounded">
<span className="text-mono-data font-mono-data text-on-surface">VEC_0x7D5E1...</span>
<span className="text-mono-data font-mono-data text-tertiary">0.941</span>
</div>
</div>
</div>
</div>
</div>
</main> </> );
};
